import { SummaryStats, Deal, IndustryData, MonthlyData, YearlyData } from './processing/types';

export const sampleData = {
  summaryStats: {
    totalDeals: 127,
    completedDeals: 89,
    pendingDeals: 25,
    terminatedDeals: 13,
    successRate: 70.1,
    totalValue: 15234.5, // millions
    avgDealSize: 120.0,
    medianDealSize: 45.2,
    largestDeal: {
      dealType: 'Acquisition',
      announceDate: new Date('2024-03-15'),
      targetName: 'Grupo Financiero XYZ',
      acquirerName: 'Global Capital Partners',
      announcedValue: 2340.5,
      paymentType: 'Cash',
      dealStatus: 'Completed',
      targetIndustry: 'Financial Services',
      completionDate: new Date('2024-06-30'),
    } as Deal,
    mostActiveSector: 'Technology',
  } as SummaryStats,
  
  industryData: [
    { industry: 'Technology', count: 34, totalValue: 4520.3, percentage: 26.8, avgDealSize: 133.0 },
    { industry: 'Financial Services', count: 28, totalValue: 5234.1, percentage: 22.0, avgDealSize: 186.9 },
    { industry: 'Healthcare', count: 22, totalValue: 2100.5, percentage: 17.3, avgDealSize: 95.5 },
    { industry: 'Consumer & Retail', count: 18, totalValue: 1520.8, percentage: 14.2, avgDealSize: 84.5 },
    { industry: 'Energy', count: 15, totalValue: 1342.0, percentage: 11.8, avgDealSize: 89.5 },
    { industry: 'Others', count: 10, totalValue: 516.8, percentage: 7.9, avgDealSize: 51.7 },
  ] as IndustryData[],
  
  monthlyData: [
    { month: 'Enero', monthNumber: 1, year: 2024, count: 8, totalValue: 1234.5 },
    { month: 'Febrero', monthNumber: 2, year: 2024, count: 12, totalValue: 980.3 },
    { month: 'Marzo', monthNumber: 3, year: 2024, count: 15, totalValue: 2890.1 },
    { month: 'Abril', monthNumber: 4, year: 2024, count: 10, totalValue: 1120.7 },
    { month: 'Mayo', monthNumber: 5, year: 2024, count: 9, totalValue: 890.4 },
    { month: 'Junio', monthNumber: 6, year: 2024, count: 14, totalValue: 1567.2 },
    { month: 'Julio', monthNumber: 7, year: 2024, count: 11, totalValue: 1234.0 },
    { month: 'Agosto', monthNumber: 8, year: 2024, count: 7, totalValue: 678.9 },
    { month: 'Septiembre', monthNumber: 9, year: 2024, count: 13, totalValue: 1450.3 },
    { month: 'Octubre', monthNumber: 10, year: 2024, count: 10, totalValue: 1123.4 },
    { month: 'Noviembre', monthNumber: 11, year: 2024, count: 9, totalValue: 987.6 },
    { month: 'Diciembre', monthNumber: 12, year: 2024, count: 9, totalValue: 1077.1 },
  ] as MonthlyData[],
  
  yearlyComparison: [
    {
      year: 2023,
      dealCount: 98,
      totalValue: 12340.5,
      completedDeals: 72,
      pendingDeals: 15,
      terminatedDeals: 11,
      successRate: 73.5,
      avgDealSize: 125.9,
    },
    {
      year: 2024,
      dealCount: 127,
      totalValue: 15234.5,
      completedDeals: 89,
      pendingDeals: 25,
      terminatedDeals: 13,
      successRate: 70.1,
      avgDealSize: 120.0,
    },
  ] as YearlyData[],
  
  topDeals: [
    {
      dealType: 'Acquisition',
      announceDate: new Date('2024-03-15'),
      targetName: 'Grupo Financiero XYZ',
      acquirerName: 'Global Capital Partners',
      announcedValue: 2340.5,
      paymentType: 'Cash',
      dealStatus: 'Completed',
      targetIndustry: 'Financial Services',
      completionDate: new Date('2024-06-30'),
    },
    {
      dealType: 'Merger',
      announceDate: new Date('2024-05-22'),
      targetName: 'Tech Solutions SA',
      acquirerName: 'Innovation Holdings',
      announcedValue: 1890.3,
      paymentType: 'Stock',
      dealStatus: 'Completed',
      targetIndustry: 'Technology',
      completionDate: new Date('2024-09-15'),
    },
    {
      dealType: 'Acquisition',
      announceDate: new Date('2024-07-10'),
      targetName: 'Farmacias Unidos',
      acquirerName: 'Healthcare International',
      announcedValue: 1234.7,
      paymentType: 'Cash & Stock',
      dealStatus: 'Pending',
      targetIndustry: 'Healthcare',
    },
    {
      dealType: 'Acquisition',
      announceDate: new Date('2024-02-28'),
      targetName: 'Retail México',
      acquirerName: 'Consumer Brands Corp',
      announcedValue: 987.2,
      paymentType: 'Cash',
      dealStatus: 'Completed',
      targetIndustry: 'Consumer & Retail',
      completionDate: new Date('2024-05-20'),
    },
    {
      dealType: 'Merger',
      announceDate: new Date('2024-09-05'),
      targetName: 'Energía Solar MX',
      acquirerName: 'Green Energy Partners',
      announcedValue: 856.4,
      paymentType: 'Stock',
      dealStatus: 'Pending',
      targetIndustry: 'Energy',
    },
  ] as Deal[],
};