import { ReportData } from './types';

export const mockReportData: ReportData = {
  '0_1': {
    Market_Overview_Title: 'M&A ECM and DCM Market Overview - Mexico',
    Highlight_1: 'Fibra Next completed its IPO in July 2025 raising MXN 8000 million the largest public offering in Mexico in over six years',
    Highlight_2: "32 M&A transactions completed in 2025 highlighting Pinfra's sale of Altamira Port for over USD 800 million",
    Article_Title: 'The Return of Large Offerings to the BMV',
    Article_Author: 'Javier Gayol',
    Author_Professional_Title: 'Head of Investment Banking GBM',
    Author_Photo: null,
    Article_Content: "The successful placement of Fibra Next with 8000 million pesos raised (~USD 431 million) not only marks the largest public offering in Mexico in over six years but also sends a clear signal: the Mexican capital market has appetite and capacity for large-scale operations when attractive assets and solid structures are presented. Fibra Next's industrial portfolio together with a well-defined growth strategy managed to capture the interest of national and international investors in an environment where IPOs had practically disappeared. Beyond the amount raised this IPO could become a catalyst for other companies to consider going public reactivating the flow of new issuances and returning prominence to the Mexican Stock Exchange on the global capital radar. If it manages to consolidate its expansion plan and generate competitive returns Fibra Next will not only be remembered for its size but for having reignited the engine of placements in Mexico.",
  },
  '0_2_A': {
    Table_Title: 'Mergers and Acquisitions Summary in Mexico 2025',
    Summary_Paragraph: 'As of August 2025, 32 transactions of Mexican companies were completed, with an aggregate value of MXN 3,549 million',
    Chart_Title: 'Number of company transactions in Mexico by month - YTD 2025',
    Chart_Footnote: 'Figures include only Mexican companies acquired',
    Data: [
      { Month: 'January', Number_of_Transactions: 8 },
      { Month: 'February', Number_of_Transactions: 0 },
      { Month: 'March', Number_of_Transactions: 1 },
      { Month: 'April', Number_of_Transactions: 5 },
      { Month: 'May', Number_of_Transactions: 4 },
      { Month: 'June', Number_of_Transactions: 4 },
      { Month: 'July', Number_of_Transactions: 7 },
      { Month: 'August', Number_of_Transactions: 3 },
    ],
  },
  '0_2_B': {
    Summary_Paragraph: 'As of August 2025, the industrial sector has led M&A activity, with 7 transactions of Mexican companies, equivalent to 22% of total transactions for the year',
    Chart_Title: 'Transactions of Mexican companies by industry - YTD 2025',
    Data: [
      { Industry: 'Materials', Percentage: 16 },
      { Industry: 'Industrial', Percentage: 22 },
      { Industry: 'Consumer Discretionary', Percentage: 9 },
      { Industry: 'Consumer Staples', Percentage: 3 },
      { Industry: 'Financial', Percentage: 9 },
      { Industry: 'Technology', Percentage: 6 },
      { Industry: 'Communications', Percentage: 9 },
      { Industry: 'Energy', Percentage: 6 },
      { Industry: 'Real Estate & Materials', Percentage: 3 },
      { Industry: 'Real Estate', Percentage: 16 },
    ],
  },
  '0_3_A': {
    Section_Title: 'Capital Markets Outlook in Mexico 2025 Long-term Listed Debt',
    Total_Volume_YTD_2025: 'MXN 86,860 million',
    Featured_Issuance_Name: 'Naturgy (NM 25 & NM 25-2)',
    Featured_Issuance_Details: 'Demand: 3.4x; Rate: Variable TIIE + 63 bps (3 years) & Fixed 9.98% (7 years)',
    Footnote: 'Figures include only long-term corporate issuances',
    Data: [
      { Category: 'Fixed Rate', Value: 60 },
      { Category: 'Variable Rate', Value: 40 },
      { Category: 'AAA Rating', Value: 85 },
      { Category: 'AA Rating', Value: 15 },
      { Category: 'A Rating', Value: 0 },
    ],
  },
  '0_3_B': {
    Section_Title: 'Equity Issuances IPOs, Follow-Ons & Rights Offerings',
    Total_Volume_YTD_2025: 'MXN 13,148 million',
    Featured_Issuance_Name: 'Fibra Next',
    Featured_Issuance_Amount: 'MXN 8,000 million',
    Footnote: 'Figures include equity issuances made by companies, FIBRAs and FIBRAs E; does not consider CKDs or CERPIs',
    Data: [
      { Category: 'IPOs 2025 YTD', Value: 'MXN 8,000 million' },
      { Category: 'Follow-Ons/Rights Offerings 2025 YTD', Value: 'MXN 5,148 million' },
    ],
  },
  '1_0_A': {
    Table_Title: 'Mergers and Acquisitions Summary in Mexico - Number of transactions and accumulated value of companies in Mexico - Last 5 years (2020 - 2025 YTD)',
    Data: [
      { Year: '2020', Number_of_Transactions: 59, Accumulated_Transaction_Value_USD_MM: 1932 },
      { Year: '2021', Number_of_Transactions: 90, Accumulated_Transaction_Value_USD_MM: 11145 },
      { Year: '2022', Number_of_Transactions: 91, Accumulated_Transaction_Value_USD_MM: 4457 },
      { Year: '2023', Number_of_Transactions: 72, Accumulated_Transaction_Value_USD_MM: 8914 },
      { Year: '2024', Number_of_Transactions: 64, Accumulated_Transaction_Value_USD_MM: 10165 },
      { Year: '2024 YTD', Number_of_Transactions: 34, Accumulated_Transaction_Value_USD_MM: 7978 },
      { Year: '2025 YTD', Number_of_Transactions: 29, Accumulated_Transaction_Value_USD_MM: 3549 },
    ],
  },
  '1_0_B': {
    Table_Title: 'Accumulated transaction value by industry - 2020 - 2024',
    Data: [
      { Industry: 'Utilities', Percentage: 22 },
      { Industry: 'Communications', Percentage: 19 },
      { Industry: 'Real Estate', Percentage: 13 },
      { Industry: 'Financial', Percentage: 12 },
      { Industry: 'Consumer Staples', Percentage: 7 },
      { Industry: 'Materials', Percentage: 6 },
      { Industry: 'Energy', Percentage: 6 },
      { Industry: 'Consumer Discretionary', Percentage: 5 },
      { Industry: 'Health', Percentage: 3 },
      { Industry: 'Other', Percentage: 3 },
      { Industry: 'Industrial', Percentage: 2 },
      { Industry: 'Technology', Percentage: 2 },
    ],
  },
  '1_1': {
    Table_Title: 'Transactions in Mexico 2025 YTD',
    Footnote: 'Figures include only Mexican acquired companies',
    Data: [
      { Target: 'CEMEX Dominicana', Industry: 'Materials', Buyer: 'Cementos Progreso', Seller: 'Cemex', Date: '1/31/2025', Amount_USD_MM: '950', Percentage_Acquired: '100' },
      { Target: 'Ovniver', Industry: 'Materials', Buyer: 'Cie de Saint-Gobain', Seller: 'ND', Date: '1/15/2025', Amount_USD_MM: '815', Percentage_Acquired: '100' },
      { Target: 'ALEATICA', Industry: 'Industrial', Buyer: 'IFM Investors', Seller: 'ND', Date: '3/26/2025', Amount_USD_MM: '496', Percentage_Acquired: '14' },
      { Target: 'Spare parts business/KUO', Industry: 'Consumer Staples', Buyer: 'Fras-Le', Seller: 'Grupo KUO', Date: '1/15/2025', Amount_USD_MM: '389', Percentage_Acquired: '100' },
      { Target: 'Servicios Corporativos Javer', Industry: 'Consumer Staples', Buyer: 'Vinte Viviendas Integrales', Seller: 'ND', Date: '4/25/2025', Amount_USD_MM: '348', Percentage_Acquired: '100' },
      { Target: 'Solistica', Industry: 'Industrial', Buyer: 'Grupo Traxion', Seller: 'Fomento Economico Mexicano', Date: '4/3/2025', Amount_USD_MM: '225', Percentage_Acquired: '100' },
      { Target: 'Portfolio of 2 warehouses/Nuevo Leon', Industry: 'Real Estate', Buyer: 'Fibra MTY', Seller: 'ND', Date: '6/18/2025', Amount_USD_MM: '73', Percentage_Acquired: '100' },
      { Target: 'Tejieres Del Futuro', Industry: 'Financial', Buyer: 'Grupo Financiero Banorte', Seller: 'Rappi', Date: '4/5/2025', Amount_USD_MM: '50', Percentage_Acquired: '54' },
      { Target: 'Bonanza Gold Mine Project', Industry: 'Materials', Buyer: 'Industrias Penoles', Seller: 'Asia Broadband', Date: '5/1/2025', Amount_USD_MM: '15', Percentage_Acquired: '100' },
      { Target: 'San Jose mine/Oaxaca', Industry: 'Technology', Buyer: 'Rio Ingenieria y Construccion', Seller: 'Fortuna Mining', Date: '7/3/2025', Amount_USD_MM: '7', Percentage_Acquired: '100' },
      { Target: 'Destileria Los Danzantes', Industry: 'Communications', Buyer: 'Emperador', Seller: 'ND', Date: '7/24/2025', Amount_USD_MM: '4', Percentage_Acquired: '62' },
    ],
  },
  '2_0_A': {
    Section_Title: 'Debt Issuance Summary in Mexico',
    Chart_Title: 'Local amount issued by rate (2022 - 2025 YTD)',
    Data: [
      { Year: '2022', Fixed_Rate_Percentage: 61, Variable_Rate_Percentage: 0, Total_Amount_MXN_MM: 103477 },
      { Year: '2023', Fixed_Rate_Percentage: 64, Variable_Rate_Percentage: 0, Total_Amount_MXN_MM: 112050 },
      { Year: '2024', Fixed_Rate_Percentage: 63, Variable_Rate_Percentage: 0, Total_Amount_MXN_MM: 123334 },
      { Year: '2025 YTD', Fixed_Rate_Percentage: 60, Variable_Rate_Percentage: 0, Total_Amount_MXN_MM: 86860 },
    ],
  },
  '2_0_B': {
    Section_Title: 'Debt Issuance Summary in Mexico',
    Chart_Title: 'Issuances by credit rating (2022 - 2025 YTD)',
    Data: [
      { Year: '2022', AAA_Percentage: 68, AA_Percentage: 24, A_Percentage: 0, Total_Amount_MXN_MM: 103477 },
      { Year: '2023', AAA_Percentage: 81, AA_Percentage: 17, A_Percentage: 0, Total_Amount_MXN_MM: 112050 },
      { Year: '2024', AAA_Percentage: 80, AA_Percentage: 10, A_Percentage: 0, Total_Amount_MXN_MM: 123334 },
      { Year: '2025 YTD', AAA_Percentage: 85, AA_Percentage: 15, A_Percentage: 0, Total_Amount_MXN_MM: 86860 },
    ],
  },
  '2_0_C': {
    Section_Title: 'Rate Outlook',
    Chart_Title: 'MBONO Yield Projection',
    Data: [
      { Term: '1M', Latest: 7, _6M_Projection: 9, _12M_Projection: 10 },
      { Term: '3M', Latest: 8, _6M_Projection: 9, _12M_Projection: 10 },
      { Term: '6M', Latest: 8, _6M_Projection: 9, _12M_Projection: 10 },
      { Term: '1Y', Latest: 8, _6M_Projection: 9, _12M_Projection: 10 },
      { Term: '2Y', Latest: 7, _6M_Projection: 9, _12M_Projection: 10 },
      { Term: '3Y', Latest: 8, _6M_Projection: 9, _12M_Projection: 9 },
      { Term: '4Y', Latest: 8, _6M_Projection: 9, _12M_Projection: 9 },
      { Term: '5Y', Latest: 8, _6M_Projection: 9, _12M_Projection: 9 },
      { Term: '8Y', Latest: 9, _6M_Projection: 9, _12M_Projection: 9 },
      { Term: '10Y', Latest: 9, _6M_Projection: 9, _12M_Projection: 9 },
      { Term: '15Y', Latest: 9, _6M_Projection: 10, _12M_Projection: 10 },
      { Term: '20Y', Latest: 9, _6M_Projection: 10, _12M_Projection: 10 },
      { Term: '25Y', Latest: 9, _6M_Projection: 10, _12M_Projection: 10 },
      { Term: '30Y', Latest: 9, _6M_Projection: 10, _12M_Projection: 10 },
    ],
  },
  '2_0_D': {
    Section_Title: 'Rate Outlook',
    Chart_Title: 'TIIE Yield Projection',
    Data: [
      { Term: '1M', Latest: 8, _6M_Projection: null, _12M_Projection: null },
      { Term: '2M', Latest: 7, _6M_Projection: null, _12M_Projection: null },
      { Term: '3M', Latest: 7, _6M_Projection: 9, _12M_Projection: 10 },
      { Term: '6M', Latest: 7, _6M_Projection: 9, _12M_Projection: 10 },
      { Term: '9M', Latest: 7, _6M_Projection: 8, _12M_Projection: 10 },
      { Term: '1Y', Latest: 7, _6M_Projection: 8, _12M_Projection: 9 },
      { Term: '2Y', Latest: 7, _6M_Projection: 8, _12M_Projection: 9 },
      { Term: '3Y', Latest: 7, _6M_Projection: 8, _12M_Projection: 8 },
      { Term: '4Y', Latest: 7, _6M_Projection: 8, _12M_Projection: 8 },
      { Term: '5Y', Latest: 7, _6M_Projection: 8, _12M_Projection: 8 },
      { Term: '7Y', Latest: 8, _6M_Projection: 8, _12M_Projection: 8 },
      { Term: '10Y', Latest: 8, _6M_Projection: 8, _12M_Projection: 8 },
      { Term: '15Y', Latest: 8, _6M_Projection: 9, _12M_Projection: 9 },
      { Term: '20Y', Latest: 8, _6M_Projection: 9, _12M_Projection: 9 },
      { Term: '30Y', Latest: 8, _6M_Projection: 8, _12M_Projection: 9 },
    ],
  },
  '2_1': {
    Section_Title: 'Debt Issuances in Mexico 2025',
    Data: [
      { Issuer: 'GAP', Issue_Date: '04/02/25', Maturity_Date: '04/03/32', Term_Years: 7, Amount_MXN_MM: 3000, Rating_Fitch_SP_Moodys_HR: 'mxAAA AAA.mx', Rate_Reference: 'Fixed', IPT: 'MBONO 31', Spread_bps: '8.68%' },
      { Issuer: 'GAP', Issue_Date: '04/02/25', Maturity_Date: '01/02/28', Term_Years: 3, Amount_MXN_MM: 3000, Rating_Fitch_SP_Moodys_HR: 'mxAAA AAA.mx', Rate_Reference: 'Variable', IPT: 'TIIE FONDEO', Spread_bps: '50' },
      { Issuer: 'BIMBO', Issue_Date: '14/02/25', Maturity_Date: '06/02/32', Term_Years: 7, Amount_MXN_MM: 12762, Rating_Fitch_SP_Moodys_HR: 'mxAAA AAA(mex)', Rate_Reference: 'Fixed', IPT: 'MBONO 31-33', Spread_bps: '9.76%' },
      { Issuer: 'BIMBO', Issue_Date: '14/02/25', Maturity_Date: '11/02/28', Term_Years: 3, Amount_MXN_MM: 2238, Rating_Fitch_SP_Moodys_HR: 'mxAAA AAA(mex)', Rate_Reference: 'Variable', IPT: 'TIIE FONDEO', Spread_bps: '34' },
      { Issuer: 'ELEKTRA', Issue_Date: '27/03/25', Maturity_Date: '16/07/26', Term_Years: 1, Amount_MXN_MM: 2085, Rating_Fitch_SP_Moodys_HR: 'HR AA AA/M AA-.mx', Rate_Reference: 'Variable', IPT: 'TIIE 28', Spread_bps: '165' },
      { Issuer: 'MOLYMET', Issue_Date: '28/03/25', Maturity_Date: '22/03/30', Term_Years: 5, Amount_MXN_MM: 2500, Rating_Fitch_SP_Moodys_HR: 'AAA(mex) HR AAA', Rate_Reference: 'Variable', IPT: 'TIIE FONDEO', Spread_bps: '129' },
      { Issuer: 'ORBIA', Issue_Date: '11/04/25', Maturity_Date: '07/04/28', Term_Years: 3, Amount_MXN_MM: 3191, Rating_Fitch_SP_Moodys_HR: 'AAA(mex) HR AAA', Rate_Reference: 'Variable', IPT: 'TIIE FONDEO', Spread_bps: '95' },
      { Issuer: 'ORBIA', Issue_Date: '11/04/25', Maturity_Date: '30/03/35', Term_Years: 10, Amount_MXN_MM: 3034, Rating_Fitch_SP_Moodys_HR: 'AAA(mex) HR AAA', Rate_Reference: 'Fixed', IPT: 'MBONO 34-36', Spread_bps: '9.43%' },
      { Issuer: 'FERROMX', Issue_Date: '12/05/25', Maturity_Date: '23/10/28', Term_Years: 4, Amount_MXN_MM: 5500, Rating_Fitch_SP_Moodys_HR: 'mxAAA AAA(mex)', Rate_Reference: 'Variable', IPT: 'TIIE FONDEO', Spread_bps: '47' },
      { Issuer: 'FSHOP', Issue_Date: '20/05/25', Maturity_Date: '11/11/31', Term_Years: 7, Amount_MXN_MM: 700, Rating_Fitch_SP_Moodys_HR: 'A+(mex) HR AA', Rate_Reference: 'Fixed', IPT: 'UDIBONO 2031', Spread_bps: '5.11%' },
      { Issuer: 'FUNO', Issue_Date: '30/05/25', Maturity_Date: '26/05/28', Term_Years: 3, Amount_MXN_MM: 3700, Rating_Fitch_SP_Moodys_HR: 'AAA(mex) HR AAA', Rate_Reference: 'Variable', IPT: 'TIIE FONDEO', Spread_bps: '125' },
    ],
  },
  '3_0_A': {
    Section_Title: 'Equity Issuance Summary in Mexico',
    Chart_Title: 'Number of transactions and accumulated value of IPOs in Mexico - Last 5 years (2020 - 2025 YTD)',
    Data: [
      { Year: '2020', Number_of_Transactions: 2, Accumulated_Value_MXN_MM: 12687 },
      { Year: '2021', Number_of_Transactions: 2, Accumulated_Value_MXN_MM: 28927 },
      { Year: '2022', Number_of_Transactions: 3, Accumulated_Value_MXN_MM: 2454 },
      { Year: '2023', Number_of_Transactions: 3, Accumulated_Value_MXN_MM: 9628 },
      { Year: '2024', Number_of_Transactions: 0, Accumulated_Value_MXN_MM: 0 },
      { Year: '2025 YTD', Number_of_Transactions: 2, Accumulated_Value_MXN_MM: 4500 },
    ],
  },
  '3_0_B': {
    Section_Title: 'Equity Issuance Summary in Mexico',
    Chart_Title: 'IPOs by issuer type - YTD 2025',
    Data: [
      { Issuer_Type: 'FIBRAs E', Percentage: 100 },
      { Issuer_Type: 'FIBRAs', Percentage: 0 },
      { Issuer_Type: 'Companies', Percentage: 0 },
    ],
  },
  '3_0_C': {
    Section_Title: 'Equity Issuance Summary in Mexico',
    Chart_Title: 'Number of transactions and accumulated value of Follow Ons in Mexico - Last 5 years (2020 - 2025 YTD)',
    Data: [
      { Year: '2020', Number_of_Transactions: 1, Accumulated_Value_MXN_MM: 17192 },
      { Year: '2021', Number_of_Transactions: 1, Accumulated_Value_MXN_MM: 779 },
      { Year: '2022', Number_of_Transactions: 1, Accumulated_Value_MXN_MM: 13110 },
      { Year: '2023', Number_of_Transactions: 3, Accumulated_Value_MXN_MM: 10040 },
      { Year: '2024', Number_of_Transactions: 5, Accumulated_Value_MXN_MM: 25677 },
      { Year: '2025 YTD', Number_of_Transactions: 1, Accumulated_Value_MXN_MM: 5148 },
    ],
  },
  '3_0_D': {
    Section_Title: 'Equity Issuance Summary in Mexico',
    Chart_Title: 'Number of transactions and accumulated value of Rights Offerings in Mexico - Last 5 years (2020 - 2025 YTD)',
    Data: [
      { Year: '2020', Number_of_Transactions: 4, Accumulated_Value_MXN_MM: 9816 },
      { Year: '2021', Number_of_Transactions: 2, Accumulated_Value_MXN_MM: 2700 },
      { Year: '2022', Number_of_Transactions: 2, Accumulated_Value_MXN_MM: 8784 },
      { Year: '2023', Number_of_Transactions: 8, Accumulated_Value_MXN_MM: 2368 },
      { Year: '2024', Number_of_Transactions: 5, Accumulated_Value_MXN_MM: 4252 },
      { Year: '2025 YTD', Number_of_Transactions: 0, Accumulated_Value_MXN_MM: 0 },
    ],
  },
  '3_1': {
    Section_Title: 'Equity Issuances in Mexico 2025',
    Data: [
      { Instrument_Type: 'Fibra E', Ticker: 'XFRA', Series: '22', Placement_Type: 'Follow-on', Payment_Date: '02/06/25', Shares_Issued_MM: 257, Placement_Price_MXN: 20, Amount_Placed_MXN_MM: 5148 },
      { Instrument_Type: 'Fibra E', Ticker: 'FIEMEX', Series: '25-2D', Placement_Type: 'Initial issuance (non-cash IPO)', Payment_Date: '16/06/25', Shares_Issued_MM: 21, Placement_Price_MXN: 103, Amount_Placed_MXN_MM: 2208 },
      { Instrument_Type: 'Fibra E', Ticker: 'FIEMEX', Series: '25D', Placement_Type: 'Initial issuance (non-cash IPO)', Payment_Date: '16/06/25', Shares_Issued_MM: 22, Placement_Price_MXN: 103, Amount_Placed_MXN_MM: 2293 },
      { Instrument_Type: 'Fibra E', Ticker: 'FNEXT', Series: 'NEXT25', Placement_Type: 'Initial issuance', Payment_Date: '24/07/25', Shares_Issued_MM: 80, Placement_Price_MXN: 100, Amount_Placed_MXN_MM: 8000 },
    ],
  },
  '4_0': {
    Section_Title: 'Legal Notice',
    Legal_Notice_Content: 'The information contained herein (the "Information") has been prepared by Grupo Bursátil Mexicano, S.A. de C.V., Casa de Bolsa ("GBM"), in its capacity as possible advisor and/or placement intermediary for Grupo Bafar, S.A.B. de C.V. (the "Company"). The Information is presented for informational purposes only and is not intended to be complete or exhaustive. This presentation and the Information contained therein does not constitute an offer or proposal nor does it create any obligation on the part of the Company and/or GBM and their respective clients, the persons who receive it, or any third party. There is no representation or warranty, express or implied, regarding the accuracy, impartiality or completeness of the Information. The Information may contain forward-looking statements about the future performance of an asset or business that reflect GBM\'s expectations and projections, which may differ substantially from actual results due to different factors, risks and uncertainties. Likewise, the Information is subject to updates, changes, verifications, corrections and adjustments from time to time and GBM assumes no obligation to update it or to inform any person of such changes. Any person receiving this presentation, upon receiving it, acknowledges that: (i) the Information contained herein is for informational purposes only, and does not cover, nor is it intended to cover everything required to evaluate an investment, (ii) they will not base their decision to buy, sell, carry out any transaction, make investment decisions or recommend an investment to third parties, based on the Information contained herein, and (iii) waives any rights they may have in relation to the Information included in this presentation. It is expected that recipients of this Information make their own decisions without relying on this document. Without prejudice to liability for fraud, GBM and the Company disclaim any liability that may be attributed to them based on this document or any other written or oral information provided in connection therewith and any errors therein and/or omissions therefrom. Therefore, this presentation should not be interpreted as an agreement between the parties, nor as an offer to invest, buy or sell, nor will it grant rights to its recipients. The Information contained herein should not be considered as legal or tax advice. Any interested person should consult their own legal and tax advisors. Under no circumstances should the receiving parties of this Information contact any of the Company\'s directors, officers or employees, either directly or indirectly, without the express written consent of GBM. All communications, inquiries and requests for information must be directed to GBM. Therefore, GBM and/or the Company or any of their respective officers, employees or agents have no responsibility or obligation for the truthfulness or variation of the Information. The publication and delivery of this presentation should not be considered as a commitment by GBM and/or the Company to carry out any transaction. This presentation and its content are the property of GBM and may not be reproduced or disseminated, in whole or in part, without the prior written consent of GBM. By the mere fact of attending this presentation and accepting to view the materials presented, you agree to be subject to the limitations described herein.',
  },
};
